### ISSUE TITLE
Feat: 기록 페이지 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-POPTATO-DEV/illdan_iOS#31]
## TODO

- [x] 기록 페이지 구현
- [x] 기록 조회 API 연결
- [x] 바텀시트 수정
- [x] 마감기한 설정 캘린더 구현
